### PR TITLE
Fix GitLab group support and pagination

### LINKED ISSUE #8: [GitLab] UserWarning: Calling a `list()` method without specifying `get_all=True` or `iterator=True` will return a maximum of 20 items
I've got a GitLab provider a try (big thanks @robrobert99 for your contribution!) and for some "sample repo", I see the following warning in the logs:

> datascraper    | Fetching repository onboarding statuses for 1 repos (this may take several minutes) ...
  0%|                                                     | 0/1 [00:00<?, ?it/s]/app/client_impl/gitlab_client.py:71: UserWarning: Calling a `list()` method without specifying `get_all=True` or `iterator=True` will return a maximum of 20 items. Your query returned 20 of many items. See https://python-gitlab.readthedocs.io/en/v4.6.0/api-usage.html#pagination for more details. If this was done intentionally, then this warning can be supressed by adding the argument `get_all=False` to the `list()` call. (python-gitlab: /app/client_impl/gitlab_client.py:71)
> datascraper    |   gl_commits: List[ProjectCommit] = self._gl_project.commits.list(since=since.isoformat())

I believe, for larger repos "20 items" for commits is not enough (for number of PRs/MRs rather as well).

(btw, I'm still fighting with metabase using H2 instead of Postgres, so I don't see the result, but that could be due to the networking changes I had to introduce, so I will ask about that once analyzed)

### PR DESCRIPTION
**Pull request by MShekow**
Fixes #8 and #10

@szpak please try it out and provide feedback, if possible

### CODE REVIEW

**Comment by szpak** [comment]
I've just run it and it worked, thanks!

All direct repos and from the subgroups were discovered when a `group/subgroup` pattern was provided in `REPOS`. It took some time to fetch the PRs (and even more for get the onboarding statuses - even up to 10 second per repo), but it was still <1 minute for ~15 repos and ~150 MRs.

The scrapper hit a few times "Unable to parse dependency table: expected Link, but got", but it is not related and I will examine that and I will report it separately with sample MRs.

It would be probably good to have @robrobert99 run it with his repos, but for me it looks ok :)
(btw, I haven't tested the `user:` case)

**Comment by MShekow** [comment]
Thank you. There were a few more problems with `user:` repos, which I fixed.

**Comment by robrobert99** [comment]
It worked for me with my repositories as well, but it also worked with the first implementation of the GitLab client. I noticed no difference in performance and had no error logs. However, I had one warning for `gitlab_client.py` at line 71, where the `get_all=True` parameter could be set as well.

**Comment by MShekow** [comment]
> It worked for me with my repositories as well, but it also worked with the first implementation of the GitLab client. I noticed no difference in performance and had no error logs. However, I had one warning for `gitlab_client.py` at line 71, where the `get_all=True` parameter could be set as well.

Hey, thanks for your feedback. However, I'm confused about line "71" in gitlab_client.py, this line calls one of my own functions, so something is off. Could you check again which specific call is affected?

**Pull request merged**
